version: '3.9'

services:
  metaserver1:
    build:
      context: ..
      dockerfile: deploy/metaserver.Dockerfile
    image: simplidfs-metaserver:v0.9.2
    environment:
      - ID=1
      - PEERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs

  metaserver2:
    build:
      context: ..
      dockerfile: deploy/metaserver.Dockerfile
    image: simplidfs-metaserver:v0.9.2
    environment:
      - ID=2
      - PEERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs

  metaserver3:
    build:
      context: ..
      dockerfile: deploy/metaserver.Dockerfile
    image: simplidfs-metaserver:v0.9.2
    environment:
      - ID=3
      - PEERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs

  node1:
    build:
      context: ..
      dockerfile: deploy/node.Dockerfile
    image: simplidfs-node:v0.9.2
    environment:
      - METASERVERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs
    depends_on:
      - metaserver1

  node2:
    build:
      context: ..
      dockerfile: deploy/node.Dockerfile
    image: simplidfs-node:v0.9.2
    environment:
      - METASERVERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs
    depends_on:
      - metaserver1

  node3:
    build:
      context: ..
      dockerfile: deploy/node.Dockerfile
    image: simplidfs-node:v0.9.2
    environment:
      - METASERVERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs
    depends_on:
      - metaserver1

  node4:
    build:
      context: ..
      dockerfile: deploy/node.Dockerfile
    image: simplidfs-node:v0.9.2
    environment:
      - METASERVERS=metaserver1,metaserver2,metaserver3
    networks:
      - simplidfs
    depends_on:
      - metaserver1

  loki:
    image: grafana/loki:2.9.3
    networks:
      - simplidfs
    volumes:
      - loki-data:/data

  grafana:
    image: grafana/grafana:9.5.2
    networks:
      - simplidfs
    depends_on:
      - loki
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  loki-data:
  grafana-data:

networks:
  simplidfs:
