// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: spiffe/workload/workload.proto

#include "spiffe/workload/workload.pb.h"
#include "spiffe/workload/workload.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SpiffeWorkloadAPI_method_names[] = {
  "/SpiffeWorkloadAPI/FetchX509SVID",
  "/SpiffeWorkloadAPI/FetchX509Bundles",
  "/SpiffeWorkloadAPI/FetchJWTSVID",
  "/SpiffeWorkloadAPI/FetchJWTBundles",
  "/SpiffeWorkloadAPI/ValidateJWTSVID",
};

std::unique_ptr< SpiffeWorkloadAPI::Stub> SpiffeWorkloadAPI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SpiffeWorkloadAPI::Stub> stub(new SpiffeWorkloadAPI::Stub(channel, options));
  return stub;
}

SpiffeWorkloadAPI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_FetchX509SVID_(SpiffeWorkloadAPI_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_FetchX509Bundles_(SpiffeWorkloadAPI_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_FetchJWTSVID_(SpiffeWorkloadAPI_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FetchJWTBundles_(SpiffeWorkloadAPI_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ValidateJWTSVID_(SpiffeWorkloadAPI_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::X509SVIDResponse>* SpiffeWorkloadAPI::Stub::FetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::X509SVIDResponse>::Create(channel_.get(), rpcmethod_FetchX509SVID_, context, request);
}

void SpiffeWorkloadAPI::Stub::async::FetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest* request, ::grpc::ClientReadReactor< ::X509SVIDResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::X509SVIDResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_FetchX509SVID_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::X509SVIDResponse>* SpiffeWorkloadAPI::Stub::AsyncFetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::X509SVIDResponse>::Create(channel_.get(), cq, rpcmethod_FetchX509SVID_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::X509SVIDResponse>* SpiffeWorkloadAPI::Stub::PrepareAsyncFetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::X509SVIDResponse>::Create(channel_.get(), cq, rpcmethod_FetchX509SVID_, context, request, false, nullptr);
}

::grpc::ClientReader< ::X509BundlesResponse>* SpiffeWorkloadAPI::Stub::FetchX509BundlesRaw(::grpc::ClientContext* context, const ::X509BundlesRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::X509BundlesResponse>::Create(channel_.get(), rpcmethod_FetchX509Bundles_, context, request);
}

void SpiffeWorkloadAPI::Stub::async::FetchX509Bundles(::grpc::ClientContext* context, const ::X509BundlesRequest* request, ::grpc::ClientReadReactor< ::X509BundlesResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::X509BundlesResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_FetchX509Bundles_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::X509BundlesResponse>* SpiffeWorkloadAPI::Stub::AsyncFetchX509BundlesRaw(::grpc::ClientContext* context, const ::X509BundlesRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::X509BundlesResponse>::Create(channel_.get(), cq, rpcmethod_FetchX509Bundles_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::X509BundlesResponse>* SpiffeWorkloadAPI::Stub::PrepareAsyncFetchX509BundlesRaw(::grpc::ClientContext* context, const ::X509BundlesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::X509BundlesResponse>::Create(channel_.get(), cq, rpcmethod_FetchX509Bundles_, context, request, false, nullptr);
}

::grpc::Status SpiffeWorkloadAPI::Stub::FetchJWTSVID(::grpc::ClientContext* context, const ::JWTSVIDRequest& request, ::JWTSVIDResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::JWTSVIDRequest, ::JWTSVIDResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FetchJWTSVID_, context, request, response);
}

void SpiffeWorkloadAPI::Stub::async::FetchJWTSVID(::grpc::ClientContext* context, const ::JWTSVIDRequest* request, ::JWTSVIDResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::JWTSVIDRequest, ::JWTSVIDResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchJWTSVID_, context, request, response, std::move(f));
}

void SpiffeWorkloadAPI::Stub::async::FetchJWTSVID(::grpc::ClientContext* context, const ::JWTSVIDRequest* request, ::JWTSVIDResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchJWTSVID_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::JWTSVIDResponse>* SpiffeWorkloadAPI::Stub::PrepareAsyncFetchJWTSVIDRaw(::grpc::ClientContext* context, const ::JWTSVIDRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::JWTSVIDResponse, ::JWTSVIDRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FetchJWTSVID_, context, request);
}

::grpc::ClientAsyncResponseReader< ::JWTSVIDResponse>* SpiffeWorkloadAPI::Stub::AsyncFetchJWTSVIDRaw(::grpc::ClientContext* context, const ::JWTSVIDRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFetchJWTSVIDRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::JWTBundlesResponse>* SpiffeWorkloadAPI::Stub::FetchJWTBundlesRaw(::grpc::ClientContext* context, const ::JWTBundlesRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::JWTBundlesResponse>::Create(channel_.get(), rpcmethod_FetchJWTBundles_, context, request);
}

void SpiffeWorkloadAPI::Stub::async::FetchJWTBundles(::grpc::ClientContext* context, const ::JWTBundlesRequest* request, ::grpc::ClientReadReactor< ::JWTBundlesResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::JWTBundlesResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_FetchJWTBundles_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::JWTBundlesResponse>* SpiffeWorkloadAPI::Stub::AsyncFetchJWTBundlesRaw(::grpc::ClientContext* context, const ::JWTBundlesRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::JWTBundlesResponse>::Create(channel_.get(), cq, rpcmethod_FetchJWTBundles_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::JWTBundlesResponse>* SpiffeWorkloadAPI::Stub::PrepareAsyncFetchJWTBundlesRaw(::grpc::ClientContext* context, const ::JWTBundlesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::JWTBundlesResponse>::Create(channel_.get(), cq, rpcmethod_FetchJWTBundles_, context, request, false, nullptr);
}

::grpc::Status SpiffeWorkloadAPI::Stub::ValidateJWTSVID(::grpc::ClientContext* context, const ::ValidateJWTSVIDRequest& request, ::ValidateJWTSVIDResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ValidateJWTSVIDRequest, ::ValidateJWTSVIDResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ValidateJWTSVID_, context, request, response);
}

void SpiffeWorkloadAPI::Stub::async::ValidateJWTSVID(::grpc::ClientContext* context, const ::ValidateJWTSVIDRequest* request, ::ValidateJWTSVIDResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ValidateJWTSVIDRequest, ::ValidateJWTSVIDResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateJWTSVID_, context, request, response, std::move(f));
}

void SpiffeWorkloadAPI::Stub::async::ValidateJWTSVID(::grpc::ClientContext* context, const ::ValidateJWTSVIDRequest* request, ::ValidateJWTSVIDResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateJWTSVID_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ValidateJWTSVIDResponse>* SpiffeWorkloadAPI::Stub::PrepareAsyncValidateJWTSVIDRaw(::grpc::ClientContext* context, const ::ValidateJWTSVIDRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ValidateJWTSVIDResponse, ::ValidateJWTSVIDRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ValidateJWTSVID_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ValidateJWTSVIDResponse>* SpiffeWorkloadAPI::Stub::AsyncValidateJWTSVIDRaw(::grpc::ClientContext* context, const ::ValidateJWTSVIDRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidateJWTSVIDRaw(context, request, cq);
  result->StartCall();
  return result;
}

SpiffeWorkloadAPI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpiffeWorkloadAPI_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SpiffeWorkloadAPI::Service, ::X509SVIDRequest, ::X509SVIDResponse>(
          [](SpiffeWorkloadAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::X509SVIDRequest* req,
             ::grpc::ServerWriter<::X509SVIDResponse>* writer) {
               return service->FetchX509SVID(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpiffeWorkloadAPI_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SpiffeWorkloadAPI::Service, ::X509BundlesRequest, ::X509BundlesResponse>(
          [](SpiffeWorkloadAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::X509BundlesRequest* req,
             ::grpc::ServerWriter<::X509BundlesResponse>* writer) {
               return service->FetchX509Bundles(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpiffeWorkloadAPI_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SpiffeWorkloadAPI::Service, ::JWTSVIDRequest, ::JWTSVIDResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SpiffeWorkloadAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::JWTSVIDRequest* req,
             ::JWTSVIDResponse* resp) {
               return service->FetchJWTSVID(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpiffeWorkloadAPI_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SpiffeWorkloadAPI::Service, ::JWTBundlesRequest, ::JWTBundlesResponse>(
          [](SpiffeWorkloadAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::JWTBundlesRequest* req,
             ::grpc::ServerWriter<::JWTBundlesResponse>* writer) {
               return service->FetchJWTBundles(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpiffeWorkloadAPI_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SpiffeWorkloadAPI::Service, ::ValidateJWTSVIDRequest, ::ValidateJWTSVIDResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SpiffeWorkloadAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ValidateJWTSVIDRequest* req,
             ::ValidateJWTSVIDResponse* resp) {
               return service->ValidateJWTSVID(ctx, req, resp);
             }, this)));
}

SpiffeWorkloadAPI::Service::~Service() {
}

::grpc::Status SpiffeWorkloadAPI::Service::FetchX509SVID(::grpc::ServerContext* context, const ::X509SVIDRequest* request, ::grpc::ServerWriter< ::X509SVIDResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SpiffeWorkloadAPI::Service::FetchX509Bundles(::grpc::ServerContext* context, const ::X509BundlesRequest* request, ::grpc::ServerWriter< ::X509BundlesResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SpiffeWorkloadAPI::Service::FetchJWTSVID(::grpc::ServerContext* context, const ::JWTSVIDRequest* request, ::JWTSVIDResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SpiffeWorkloadAPI::Service::FetchJWTBundles(::grpc::ServerContext* context, const ::JWTBundlesRequest* request, ::grpc::ServerWriter< ::JWTBundlesResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SpiffeWorkloadAPI::Service::ValidateJWTSVID(::grpc::ServerContext* context, const ::ValidateJWTSVIDRequest* request, ::ValidateJWTSVIDResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


