name: CMake

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04   # noble (libfuse 3.16.2 out of the box)

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libsodium-dev pkg-config libfuse3-dev fuse3

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build --config $BUILD_TYPE

      - name: Test
        working-directory: build
        run: ctest -C $BUILD_TYPE --output-on-failure
