name: CMake

on:
  push:          { branches: [ master, development ] }
  pull_request:  { branches: [ master, development ] }

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04  # noble snapshot

    steps:
      - uses: actions/checkout@v4

      # ---- system deps (libsodium + build tools) --------------------------
      - name: Install base packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libsodium-dev pkg-config \
                                   build-essential meson ninja-build \
                                   libudev-dev curl

      # ---- build libfuse 3.16.2 ------------------------------------------
      - name: Build & install libfuse 3.16.2
        run: |
          curl -L -o fuse-3.16.2.tar.gz \
               https://github.com/libfuse/libfuse/releases/download/fuse-3.16.2/fuse-3.16.2.tar.gz
          tar xzf fuse-3.16.2.tar.gz
          cd fuse-3.16.2
          meson setup build --prefix=/usr
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig

      # ---- project build/test --------------------------------------------
      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_POSIX_TEST_SUITE=ON

      - name: Build
        run: cmake --build build --config $BUILD_TYPE

      - name: Test
        working-directory: build
        run: ctest -C $BUILD_TYPE --output-on-failure -VV -E FuseTestEnv --timeout 1200
