name: Deploy Metaserver to GCP

on:
  push:
    tags: ['v*']

env:
  IMAGE: us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/simplidfs/simplidfs-metaserver:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1 ─ Authenticate to Google Cloud
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    # 2 ─ Wire creds into Docker *for Artifact Registry*
    - name: Configure Docker
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet

    # 3 ─ Build & Push
    - name: Build image
      run: docker build -f deploy/metaserver.Dockerfile -t $IMAGE .

    - name: Push image
      run: docker push $IMAGE

    # 4 ─ Pull + restart on the VM
    - name: Restart Metaserver service
      run: |
        gcloud compute ssh ${{ secrets.GCE_INSTANCE }} \
          --zone ${{ secrets.GCE_ZONE }} \
          --command='sudo docker pull '"$IMAGE"' && sudo systemctl restart simplidfs-metaserver'
