name: Deploy Metaserver to GCP

on:
  push:
    tags: ['v*']
  workflow_run:
    workflows: ['Tag Development Snapshot']
    types:
      - completed

env:
  GIT_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
  IMAGE: us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/simplidfs/simplidfs-metaserver:${{ env.GIT_SHA }}

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1 ─ Authenticate to Google Cloud
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    # 2 ─ Wire creds into Docker *for Artifact Registry*
    - name: Configure Docker
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet

    # 3 ─ Build & Push
    - name: Read version
      id: version
      run: echo "tag=v$(cat VERSION)" >> "$GITHUB_OUTPUT"

    - name: Build image
      run: docker build --build-arg VERSION=${{ steps.version.outputs.tag }} -f deploy/metaserver.Dockerfile -t $IMAGE .

    - name: Push image
      run: docker push $IMAGE

    - name: Get image digest
      id: digest
      run: |
        DIGEST=$(gcloud artifacts docker images describe $IMAGE --format='value(image_summary.digest)')
        echo "digest=us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/simplidfs/simplidfs-metaserver@${DIGEST}" >> "$GITHUB_OUTPUT"

    # 4 ─ Pull + restart on the VM
    - name: Restart Metaserver service
      run: |
        gcloud compute ssh ${{ secrets.GCE_INSTANCE }} \
          --zone ${{ secrets.GCE_ZONE }} \
          --command='sudo docker pull '"${{ steps.digest.outputs.digest }}"' && sudo systemctl restart simplidfs-metaserver'
